import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-gray-900 mt-12 border-t border-gray-800">
      <div className="container mx-auto px-4 py-6 text-center text-gray-500">
        <p className="text-sm">
          Disclaimer: This content is generated by an AI model and is for informational purposes only. It should not be considered as financial advice. Always conduct your own research before making any investment decisions.
        </p>
        <p className="text-xs mt-2">
          Powered by Google Gemini
        </p>
      </div>
    </footer>
  );
};

export default Footer;
